import { apiRequest } from './api.js'

export const loadCreationBootstrap = () => apiRequest('/api/creation/bootstrap', { deadlineClass: 'model' })
export const startComfyUi = () => apiRequest('/api/creation/comfyui/start', { method: 'POST', deadlineClass: 'model' })
export const loadCreationConfiguration = () => apiRequest('/api/creation/configuration')
export const discoverComfyUi = () => apiRequest('/api/creation/comfyui/discover', { deadlineClass: 'model' })
export const discoverLocalWorkflows = query => apiRequest(`/api/creation/workflows/local?query=${encodeURIComponent(query || '')}`)
export const readLocalWorkflow = path => apiRequest(`/api/creation/workflows/local/read?path=${encodeURIComponent(path)}`)
export const saveCreationEnvironment = payload => apiRequest('/api/creation/configuration/environment', { method: 'PUT', body: JSON.stringify(payload) })
export const saveWorkflowDefaults = payload => apiRequest('/api/creation/configuration/workflows', { method: 'PUT', body: JSON.stringify(payload) })
export const importCreationWorkflow = payload => apiRequest('/api/creation/workflows', { method: 'POST', body: JSON.stringify(payload) })
export const previewCreationWorkflow = prompt => apiRequest('/api/creation/workflows/preview', { method: 'POST', body: JSON.stringify({ prompt }) })
export const removeCreationWorkflow = id => apiRequest(`/api/creation/workflows/${encodeURIComponent(id)}`, { method: 'DELETE' })
export const loadCreationJob = (id) => apiRequest(`/api/creation/jobs/${encodeURIComponent(id)}`, { deadlineClass: 'read' })
export const loadCreationPreflight = (workflowId = '') => apiRequest(`/api/creation/preflight${workflowId ? `?workflow_id=${encodeURIComponent(workflowId)}` : ''}`, { deadlineClass: 'model' })
export const submitCreationJob = (payload) => apiRequest('/api/creation/jobs', { method: 'POST', body: JSON.stringify(payload), deadlineClass: 'model' })
export const confirmCreationJob = (id) => apiRequest(`/api/creation/jobs/${encodeURIComponent(id)}/confirm`, { method: 'POST', deadlineClass: 'mutation' })
export const retryCreationJob = (id) => apiRequest(`/api/creation/jobs/${encodeURIComponent(id)}/retry`, { method: 'POST', deadlineClass: 'mutation' })
export const cancelCreationJob = (id) => apiRequest(`/api/creation/jobs/${encodeURIComponent(id)}/cancel`, { method: 'POST', deadlineClass: 'mutation' })
export const uploadCreationAsset = (payload) => apiRequest('/api/creation/assets', { method: 'POST', body: JSON.stringify(payload), deadlineClass: 'mutation' })
export const saveCreationPreset = (payload) => apiRequest('/api/creation/presets', { method: 'POST', body: JSON.stringify(payload), deadlineClass: 'mutation' })
export const deleteCreationPreset = (id) => apiRequest(`/api/creation/presets/${encodeURIComponent(id)}`, { method: 'DELETE', deadlineClass: 'mutation' })
